name: Compliance Workflow

on:
    workflow_dispatch:
    schedule:
        - cron: '0 1 * * 1-5'

jobs:
    CyDig-Compliance-Workflow:
        uses: Omegapoint/cydig-reusable-workflows/.github/workflows/compliance-template.yml@main
        secrets: inherit
        permissions:
            contents: read
            pages: write
            id-token: write
