name: Test
run-name: ${{ github.actor }} is running tests
permissions:
  contents: read
  pages: read
  id-token: write

on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Upload action
        uses: actions/checkout@v4
        with:
          path: upload-action
      - name: Checkout Azure compliance action
        uses: actions/checkout@v4
        with:
           repository: Omegapoint/cydig-azure-compliance-action
           path: azure-compliance-action
      - name: Checkout compliance action
        uses: actions/checkout@v4
        with:
          repository: Omegapoint/cydig-compliance-action
          path: compliance-action
      - name: Setup node
        uses: actions/setup-node@v3

      - name: Install upload action dependencies
        run: |
          cd upload-action
          npm ci
      # - name: Install compliance action dependencies
      #   run: |
      #     cd compliance-action 
      #     npm ci
      # - name: Install azure compliance action dependencies
      #   run: |
      #     cd azure-compliance-action 
      #     npm ci

      # - name: Run upload tests
      #   run: npm run test
      # - name: Run azure compliance tests
      #   run : |
      #     cd azure-compliance-action
      #     npm run test
      # - name: Run compliance tests
      #   run : |
      #     cd compliance-action
      #     npm run test
        
      - name: Build Upload action
        run: |
          cd upload-action 
          npm run build
      # - name: Build azure compliance action
      #   run: |
      #     cd azure-compliance-action
      #     npm run build
      # - name: Build compliance action
      #   run: |
      #     cd compliance-action
      #     npm run build

      # - name: 'Az CLI login'
      #   uses: azure/login@v1
      #   with:
      #     client-id: ${{ secrets.AZURE_CLIENT_ID_DEV }}
      #     tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      #     subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID_DEV }}
      # - name: 'Run Azure Compliance Controls'
      #   uses: ./azure-compliance-action
      #   with:
      #     subscription: ${{ secrets.AZURE_SUBSCRIPTION_ID_DEV }}
      # - name: 'Run Compliance Controls'
      #   uses: ./compliance-action
      #   with:
      #     cydigConfigPath: ${{ github.workspace }}/compliance-action/src/cydigconfig.json
      #     PAT-token: ${{ secrets.MY_GITHUB_PAT }}
    
      - name: display path
        run: |
          echo ${{ github.workspace }}
          cd upload-action
          ls
      - name: 'Run Upload Action'
        uses: ./
        with:
          cydigConfigPath: ${{ github.workspace }}/upload-action/src/cydigconfig.json
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID_DEV }}
    