name: Test all actions
run-name: ${{ github.actor }} is running tests
permissions:
  contents: read
  pages: read
  id-token: write

on:
  workflow_dispatch:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Upload action
        uses: actions/checkout@v4
        with:
          path: upload-action
      - name: Checkout Azure compliance action
        uses: actions/checkout@v4
        with:
          repository: Omegapoint/cydig-azure-compliance-action
          path: azure-compliance-action
      - name: Checkout compliance action
        uses: actions/checkout@v4
        with:
          repository: Omegapoint/cydig-compliance-action
          path: compliance-action
          ref: feature/tm-and-pt-devops
      - name: Setup node
        uses: actions/setup-node@v3

      - name: Install upload action dependencies
        run: |
          cd upload-action
          npm ci
      - name: Install compliance action dependencies
        run: |
          cd compliance-action
          npm ci
      - name: Install azure compliance action dependencies
        run: |
          cd azure-compliance-action
          npm ci

      - name: Run upload tests
        run: |
          cd upload-action
           npm run test
      - name: Run azure compliance tests
        run: |
          cd azure-compliance-action
          npm run test
      - name: Run compliance tests
        run: |
          cd compliance-action
          npm run test

      - name: Build Upload action
        run: |
          cd upload-action
          npm run build
      - name: Build azure compliance action
        run: |
          cd azure-compliance-action
          npm run build
      - name: Build compliance action
        run: |
          cd compliance-action
          npm run build

      - name: "Az CLI login"
        uses: azure/login@v1
        with:
          client-id: "46dd8f9f-612d-4311-a1e5-f5ee70621f38"
          tenant-id: "3b68c6c1-04d4-4e86-875f-e48fa80b9529"
          subscription-id: "15c6235f-9e0f-4073-baf4-4fd0a7913d76"
      - name: "Run Azure Compliance Controls"
        uses: ./azure-compliance-action
        with:
          subscription: "15c6235f-9e0f-4073-baf4-4fd0a7913d76"
          cydigConfigPath: ${{ github.workspace }}/azure-compliance-action/src/cydigConfig.json
      - name: "Run Compliance Controls"
        uses: ./compliance-action
        with:
          cydigConfigPath: ${{ github.workspace }}/compliance-action/src/cydigConfig.json
          PAT-token: ${{ secrets.MY_GITHUB_PAT }}
          accessTokenAzureDevOps: ${{ secrets.DEVOPS_TOKEN_WORK_ITEMS }}

      - name: Set dev func URL
        run: |
          echo "urlUpdate=${{ secrets.URL_UPLOAD_DEV }}" >> $GITHUB_ENV
          echo "updateKey=${{ secrets.CYDIG_API_KEY_DEV }}" >> $GITHUB_ENV
          echo "urlDashboard=${{ secrets.URL_DASHBOARD_DEV }}" >> $GITHUB_ENV
          echo "urlBadgeService=${{ vars.URL_BADGE_SERVICE_DEV }}" >> $GITHUB_ENV
          echo "accessKeyBadgeService=${{ vars.ACCESS_KEY_BADGES_DEV }}" >> $GITHUB_ENV

      - name: "Run Upload Action"
        uses: ./upload-action
        with:
          cydigConfigPath: ${{ github.workspace }}/upload-action/src/cydigConfig.json
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID_DEV }}
